name: material2
version: 0.0.1
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  angular2: 2.0.0-beta.0
dev_dependencies:
  angular2_testing: '^2.0.0-beta.0'
  browser: ^0.10.0
  scissors: ^0.4.1
  postcss_transformer: '^0.1.1'
  test: '^0.12.6+2'
  grinder: '^0.8.0+1'
  git: '^0.4.4+2'
  dart_dev: '^1.0.6'
  coverage: '^0.7.2'
  sass: '^0.4.2'
  peanut: '^0.0.1+2'
  dart_to_js_script_rewriter: '^0.1.0+4'
transformers:
# - sass
- scissors:
    compiledCssExtension: replace
- postcss_transformer:
    arguments:
    - use: autoprefixer
- angular2:
    entry_points: example/main.dart
- test/pub_serve:
    $include: test/**_test{.*,}.dart
- dart_to_js_script_rewriter
